"use client";

import { useState } from "react";
import type { ScanResult, TimelineResult } from "@/lib/types";

type Props = {
  scan: ScanResult | null;
  timeline: TimelineResult | null;
  consoleLines: string[];
  injected?: number;
};

export function ThreatReport({
  scan,
  timeline,
  consoleLines,
  injected = 0,
}: Props) {
  const [copied, setCopied] = useState(false);

  if (!scan) return null;

  const snap = scan;

  function buildReport() {
    const stages =
      timeline?.stages
        .map(
          (s) =>
            `  ${s.order}. ${s.label} (${Math.round(s.confidence * 100)}%)`,
        )
        .join("\n") || "  (none)";
    const intel = consoleLines
      .filter((l) => l.includes("Exa Threat Intel"))
      .slice(-5)
      .map((l) => `  ${l}`)
      .join("\n");

    return [
      "SCAMSHIELD — MESSAGE CHECK REPORT",
      `Result: ${snap.riskLevel.toUpperCase()}  |  Score: ${snap.score}/100`,
      `Summary: ${snap.summary}`,
      "",
      "Links:",
      ...(snap.urls.length ? snap.urls.map((u) => `  - ${u}`) : ["  (none)"]),
      "",
      "Warning signs:",
      ...snap.signals.map((s) => `  - ${s}`),
      "",
      "How they tried to trick you:",
      stages,
      timeline?.narrative ? `\nStory: ${timeline.narrative}` : "",
      "",
      "Web checks:",
      intel || "  (none)",
      "",
      injected > 0
        ? `Protection: ${injected.toLocaleString()} fake details sent to confuse the scammer.`
        : "Protection: not started",
      "",
      "Generated by ScamShield",
    ]
      .filter((x) => x !== "")
      .join("\n");
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(buildReport());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* ignore */
    }
  }

  return (
    <div className="rounded-2xl border border-border bg-panel p-5 shadow-sm dark:shadow-none">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="font-display text-base font-bold text-foreground">
            Save your report
          </p>
          <p className="mt-1 text-sm leading-relaxed text-muted">
            Copy a simple summary to share with family, bank support, or police.
          </p>
        </div>
        <button
          type="button"
          onClick={() => void copy()}
          className="min-h-12 w-full shrink-0 rounded-xl border border-accent/40 bg-accent-soft px-4 text-base font-semibold text-accent transition hover:bg-accent/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent sm:w-auto"
        >
          {copied ? "Copied" : "Copy report"}
        </button>
      </div>
    </div>
  );
}
