"use client";

import { useState } from "react";
import type { ScanResult, TimelineResult } from "@/lib/types";

type Props = {
  scan: ScanResult | null;
  timeline: TimelineResult | null;
  consoleLines: string[];
  injected?: number;
};

export function ThreatReport({
  scan,
  timeline,
  consoleLines,
  injected = 0,
}: Props) {
  const [copied, setCopied] = useState(false);

  if (!scan) return null;

  const snap = scan;

  function buildReport() {
    const stages =
      timeline?.stages
        .map(
          (s) =>
            `  ${s.order}. ${s.label} (${Math.round(s.confidence * 100)}%)`,
        )
        .join("\n") || "  (none)";
    const intel = consoleLines
      .filter((l) => l.includes("Exa Threat Intel"))
      .slice(-5)
      .map((l) => `  ${l}`)
      .join("\n");

    return [
      "═══════════════════════════════════════",
      "  SCAMSHIELD AI — THREAT REPORT",
      "═══════════════════════════════════════",
      `Risk: ${snap.riskLevel.toUpperCase()}  |  Verdict: ${snap.verdict}  |  Score: ${snap.score}/100`,
      `Plain: ${snap.plainSummary}`,
      `Summary: ${snap.summary}`,
      snap.malware?.detected
        ? `Malware lure: ${snap.malware.indicators.join("; ")}`
        : "",
      "",
      "URLs:",
      ...(snap.urls.length ? snap.urls.map((u) => `  - ${u}`) : ["  (none)"]),
      "",
      "Signals:",
      ...snap.signals.map((s) => `  - ${s}`),
      "",
      "Attack timeline:",
      stages,
      timeline?.narrative ? `\nNarrative: ${timeline.narrative}` : "",
      "",
      "Live intel (Exa):",
      intel || "  (none)",
      "",
      injected > 0
        ? `Honeypot: ${injected.toLocaleString()} synthetic credentials injected (simulated).`
        : "Honeypot: not armed",
      "═══════════════════════════════════════",
      "Generated by ScamShield AI · Neural Nexus",
    ]
      .filter((x) => x !== "")
      .join("\n");
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(buildReport());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* ignore */
    }
  }

  return (
    <div className="rounded-lg border border-border bg-panel/50 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="font-mono text-[10px] uppercase tracking-widest text-accent">
            Threat report
          </p>
          <p className="mt-1 text-sm text-muted">
            Judge-ready export — risk, timeline, Exa, honeypot.
          </p>
        </div>
        <button
          type="button"
          onClick={() => void copy()}
          className="min-h-11 w-full shrink-0 rounded-lg border border-accent/40 bg-accent/10 px-4 text-sm font-semibold text-accent transition hover:bg-accent/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent sm:w-auto"
        >
          {copied ? "Copied ✓" : "Copy report"}
        </button>
      </div>
    </div>
  );
}
